# Generated by Django 4.2.5 on 2023-09-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='service.message', verbose_name='Сообщение рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(to='service.client', verbose_name='Получатели рассылки'),
        ),
    ]
