# Generated by Django 4.2.5 on 2023-09-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_newsletter_message_newsletter_recipients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchlog',
            old_name='newsletter_settings',
            new_name='newsletter',
        ),
    ]
