# Generated by Django 4.2.5 on 2023-09-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_newsletter_settings_dispatchlog_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchlog',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.newsletter', verbose_name='Рассылка'),
        ),
    ]
