# Generated by Django 4.2.5 on 2023-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_log_delete_dispatchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Текст письма'),
        ),
    ]
