# Generated by Django 4.2.5 on 2023-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0014_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('once', 'Один раз'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю'),
                                            ('monthly', 'Раз в месяц')], max_length=10, verbose_name='Периодичность'),
        ),
    ]
