# Generated by Django 4.2.5 on 2023-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0015_newsletter_last_sent_at_alter_newsletter_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(
                choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')],
                max_length=10, verbose_name='Периодичность'),
        ),
    ]
